resources:
  - ./mongodb.yaml
  - ./wordle-backend-cm.yaml
  - ./wordle-frontend-nginx-cm.yaml
  - ./wordle-backend-secret.yaml
  - ./wordle-ingress-backend.yaml
  - ./wordle-ingress-frontend.yaml
  - ./wordle-backend.yaml
  - ./wordle-frontend.yaml